services:
  postgres:
    image: postgres:15-alpine
    container_name: backend_practice_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: event_broker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: backend_practice_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: secretpassword
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  pgdata:
